/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/__quiz` | `/__quiz`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/statistics` | `/statistics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alphabet` | `/alphabet`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/quiz/guess-image` | `/quiz/guess-image`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/quiz` | `/quiz`; params?: Router.UnknownInputParams; } | { pathname: `/languages`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/alphabet/[id]` | `/alphabet/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/quiz/[code]` | `/quiz/[code]`, params: Router.UnknownInputParams & { code: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/__quiz` | `/__quiz`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/statistics` | `/statistics`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/alphabet` | `/alphabet`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/quiz/guess-image` | `/quiz/guess-image`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/quiz` | `/quiz`; params?: Router.UnknownOutputParams; } | { pathname: `/languages`; params?: Router.UnknownOutputParams; } | { pathname: `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(tabs)'}/alphabet/[id]` | `/alphabet/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(tabs)'}/quiz/[code]` | `/quiz/[code]`, params: Router.UnknownOutputParams & { code: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/__quiz${`?${string}` | `#${string}` | ''}` | `/__quiz${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/statistics${`?${string}` | `#${string}` | ''}` | `/statistics${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/alphabet${`?${string}` | `#${string}` | ''}` | `/alphabet${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/quiz/guess-image${`?${string}` | `#${string}` | ''}` | `/quiz/guess-image${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/quiz${`?${string}` | `#${string}` | ''}` | `/quiz${`?${string}` | `#${string}` | ''}` | `/languages${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/__quiz` | `/__quiz`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/statistics` | `/statistics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alphabet` | `/alphabet`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/quiz/guess-image` | `/quiz/guess-image`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/quiz` | `/quiz`; params?: Router.UnknownInputParams; } | { pathname: `/languages`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/sign-up`; params?: Router.UnknownInputParams; } | `/+not-found` | `${'/(tabs)'}/alphabet/${Router.SingleRoutePart<T>}` | `/alphabet/${Router.SingleRoutePart<T>}` | `${'/(tabs)'}/quiz/${Router.SingleRoutePart<T>}` | `/quiz/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/alphabet/[id]` | `/alphabet/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/quiz/[code]` | `/quiz/[code]`, params: Router.UnknownInputParams & { code: string | number; } };
    }
  }
}
